# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  access-token:
    description: 'access token'
    required: true
  issue-label:
    description: 'Testing label'
    required: true
    default: 'nightly-testing'
  exclude-workflow-files:
    description: 'Excluded yml files'
    required: false
    default: ''
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
