# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  access-token:
    description: 'access token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  if: ${{ inputs.who-to-greet == 'Not Mona the Octocat' }}
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.access-token }}
    - ${{ inputs.who-to-greet }}
