source "https://rubygems.org"

# Include the Ruby Functions Framework as a dependency.
gem "functions_framework", "~> 0.5"

# Other function dependencies, for example:
# gem "package", "~> version"
gem "octokit", "~> 4.19"
gem "google-cloud-firestore"
