source "https://rubygems.org"

# Include the Ruby Functions Framework as a dependency.
gem "functions_framework", "~> 0.5"

# Other function dependencies, for example:
# gem "package", "~> version"
gem "octokit", :git => 'https://github.com/octokit/octokit.rb.git', :branch => '4-stable'
gem "google-cloud-firestore"
