on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was "
