name: test_issue_generation

on: [pull_request]

jobs:
  get_link:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Job Link
        run: |
          echo "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> id_artifact.txt
      - uses: actions/upload-artifact@v2
        with: 
          name: job_log_link
          path: id_artifact.txt
  dummy_job:
    needs: get_link
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Job Link
        run: |
          echo "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
      - uses: actions/download-artifact@v2
        with: 
          name: job_log_link
      - name: Add Link
        run: |
          echo -e "\nhttps://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> id_artifact.txt
      - uses: actions/upload-artifact@v2
        with: 
          name: job_log_link
          path: id_artifact.txt
      - name: run after merge
        if: github.action == 'closed' && github.event.pull_request.merged == true
        run: |
          echo "the branch is here."
          echo "${{ github.head_ref }}"
          echo "see if it works."
